In [14]:
import pandas as pd
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.preprocessing import StandardScaler

In [7]:
df = pd.read_csv("Iris.csv")
df.sample(5)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
16,17,5.4,3.9,1.3,0.4,Iris-setosa
131,132,7.9,3.8,6.4,2.0,Iris-virginica
22,23,4.6,3.6,1.0,0.2,Iris-setosa
87,88,6.3,2.3,4.4,1.3,Iris-versicolor
64,65,5.6,2.9,3.6,1.3,Iris-versicolor

In [8]:
X= df.drop(["Species"],axis = 1)
y = df["Species"]

In [9]:
X.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0   1            5.1           3.5            1.4           0.2
1   2            4.9           3.0            1.4           0.2
2   3            4.7           3.2            1.3           0.2
3   4            4.6           3.1            1.5           0.2
4   5            5.0           3.6            1.4           0.2

In [10]:
y.head()

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: Species, dtype: object

In [42]:
#JUST TO TEST THE MODEL MENe TEST KO 0.2 ki jaga 0.9 kara jise accuracy and evaluation bekar aaye
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.9 ,random_state = 42)

In [43]:
Scaler = StandardScaler()
X_train = Scaler.fit_transform(X_train)
X_test = Scaler.transform(X_test)

In [44]:
# training model on LogisticREgression
lr = LogisticRegression(max_iter = 200)
lr.fit(X_train,y_train)

LogisticRegression(max_iter=200)

In [45]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train,y_train)

KNeighborsClassifier()

In [46]:
nv = GaussianNB()
nv.fit(X_train,y_train)

GaussianNB()

In [47]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

models = {'Logistic Regression': lr, 'KNN': knn, 'Naive Bayes': nv}

for name, model in models.items():
    y_pred = model.predict(X_test)
    print(f"\n{name}")
    print("Accuracy:", accuracy_score(y_test, y_pred))
    
    print("cm:", confusion_matrix(y_test, y_pred))

    print("classification report:", classification_report(y_test, y_pred))

Logistic Regression
Accuracy: 0.9629629629629629
cm: [[47  1  0]
 [ 0 41  3]
 [ 0  1 42]]
classification report:                  precision    recall  f1-score   support

    Iris-setosa       1.00      0.98      0.99        48
Iris-versicolor       0.95      0.93      0.94        44
 Iris-virginica       0.93      0.98      0.95        43

       accuracy                           0.96       135
      macro avg       0.96      0.96      0.96       135
   weighted avg       0.96      0.96      0.96       135


KNN
Accuracy: 0.6296296296296297
cm: [[ 0 48  0]
 [ 0 43  1]
 [ 0  1 42]]
classification report:                  precision    recall  f1-score   support

    Iris-setosa       0.00      0.00      0.00        48
Iris-versicolor       0.47      0.98      0.63        44
 Iris-virginica       0.98      0.98      0.98        43

       accuracy                           0.63       135
      macro avg       0.48      0.65      0.54       135
   weighted avg       0.46      0.63      0.52       135


Naive Bayes
Accuracy: 0.8074074074074075
cm: [[26 19  3]
 [ 0 41  3]
 [ 0  1 42]]
classification report:                  precision    recall  f1-score   support

    Iris-setosa       1.00      0.54      0.70        48
Iris-versicolor       0.67      0.93      0.78        44
 Iris-virginica       0.88      0.98      0.92        43

       accuracy                           0.81       135
      macro avg       0.85      0.82      0.80       135
   weighted avg       0.85      0.81      0.80       135

/opt/anaconda3/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/anaconda3/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/anaconda3/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))